[WIP] Migrate to GHA
rancher/fluent-bit-package pull request #13
Opened 2024-11-06 20:30 UTC by jbiers

2024-12-05 15:01 UTC, HarrisonWAffel requested changes

2024-12-05 15:01 UTC, HarrisonWAffel commented on .github/workflows/release.yaml
> +      - name: Create Docker manifest
We need to actually mirror the upstream images into our own repository before creating the manifest. This will ensure that our manifest does not get broken if the upstream image gets deleted, as a manifest is only a reference to other images. I'm also not sure how the generation of rancher-images.txt would handle a manifest used by a chart that doesn't contain the relevant images in the same repository

2024-12-11 17:38 UTC, HarrisonWAffel requested changes
small nit on readme changes

2024-12-11 17:38 UTC, HarrisonWAffel commented on README.md
>  1. Tag a new release and push into the main branch (`master`).
We also need to add a step for updating the image-mirror repository with the new image version before cutting the tag. Might want to also specify that the tag cut in this repo has to match the one sync'd via image-mirror.

2024-12-11 18:53 UTC, jbiers commented on README.md
>  1. Tag a new release and push into the main branch (`master`).
Addressed in new commit :D

2024-12-11 18:55 UTC, HarrisonWAffel approved these changes
LGTM, thanks for handling this! We'll need to double check that the manifest annotations are setup properly once we cut a tag using this new CI. If they're missing we'll have to make minor updates to manually include the build information.

2024-12-11 18:57 UTC, merged